-- ================================================================================
--   innodb SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   innodb
--   Generated at:      Thu Apr 23 15:48:37 2009
--   Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia
-- 
-- ================================================================================

set autocommit = 0 ;

-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia

-- alter table ComputingService drop constraint computingService_fk_Id-- (is implicitly done)
-- alter table ComputingEndpoint drop constraint computingEndpoint_fk_Id-- (is implicitly done)
-- alter table ComputingShare drop constraint computingShare_fk_Id-- (is implicitly done)
-- alter table ComputingManager drop constraint computingManager_fk_Id-- (is implicitly done)
-- alter table ExecutionEnvironment drop constraint executionEnvironment_fk_Id-- (is implicitly done)
-- alter table ComputingActivity drop constraint computingActivity_fk_Id-- (is implicitly done)
-- alter table ComputingEndpoint_MVA drop constraint computingEndpoint_MVA_fk_Id-- (is implicitly done)
-- alter table ComputingManager_MVA drop constraint computingManager_MVA_fk_Id-- (is implicitly done)
-- alter table ExecutionEnvironment_MVA drop constraint executionEnvironment_MVA_fk_Id-- (is implicitly done)
-- alter table ApplicationEnvironment_MVA drop constraint applicationEnvironment_MVA_fk_Id-- (is implicitly done)
-- alter table ComputingActivity_MVA drop constraint computingActivity_MVA_fk_Id-- (is implicitly done)
-- alter table ComputingShare_MVA drop constraint computingShare_MVA_fk_Id-- (is implicitly done)
-- alter table AdminDomain drop constraint adminDomain_fk_Id-- (is implicitly done)
-- alter table UserDomain drop constraint userDomain_fk_Id-- (is implicitly done)
-- alter table AccessPolicy drop constraint accessPolicy_fk_Id-- (is implicitly done)
-- alter table MappingPolicy drop constraint mappingPolicy_fk_Id-- (is implicitly done)
-- alter table Domain_MVA drop constraint domain_MVA_fk_Id-- (is implicitly done)
-- alter table AdminDomain_MVA drop constraint adminDomain_MVA_fk_Id-- (is implicitly done)
-- alter table UserDomain_MVA drop constraint userDomain_MVA_fk_Id-- (is implicitly done)
-- alter table Policy_MVA drop constraint policy_MVA_fk_Id-- (is implicitly done)
-- alter table Endpoint_MVA drop constraint endpoint_MVA_fk_Id-- (is implicitly done)
-- alter table Service_MVA drop constraint service_MVA_fk_Id-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ApplicationEnvironmentId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ApplicationHandleId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_BenchmarkId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ToStorageServiceId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_StorageServiceCapacityId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_StorageAccessProtocolId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_StorageShareCapacityId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ToComputingServiceId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_LocationId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ContactId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ServiceId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_DomainId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_EndpointId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ShareId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ManagerId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ResourceId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_ActivityId-- (is implicitly done)
-- alter table Extension drop constraint extension_fk_PolicyId-- (is implicitly done)
-- alter table ToComputingService drop constraint toComputingService_fk_ComputingServiceId-- (is implicitly done)
-- alter table ToStorageService drop constraint toStorageService_fk_ComputingServiceId-- (is implicitly done)
-- alter table ApplicationEnvironment drop constraint applicationEnvironment_fk_ComputingManagerId-- (is implicitly done)
-- alter table Benchmark drop constraint benchmark_fk_ComputingManagerId-- (is implicitly done)
-- alter table Benchmark drop constraint benchmark_fk_ExecutionEnvironmentId-- (is implicitly done)
-- alter table ExecutionEnvironmentApplicationEnvironment drop constraint exctnvrnmntplctnvrnmnt_fk_ExecutionEnvironmentId-- (is implicitly done)
-- alter table ExecutionEnvironmentApplicationEnvironment drop constraint exctnvrnmntplctnvrnmnt_fk_ApplicationEnvironmentId-- (is implicitly done)
-- alter table ApplicationHandle drop constraint applicationHandle_fk_ApplicationEnvironmentId-- (is implicitly done)
-- alter table ToStorageService drop constraint toStorageService_fk_StorageServiceId-- (is implicitly done)
-- alter table ToComputingService drop constraint toComputingService_fk_StorageServiceId-- (is implicitly done)
-- alter table StorageServiceCapacity drop constraint storageServiceCapacity_fk_StorageServiceId-- (is implicitly done)
-- alter table StorageAccessProtocol drop constraint storageAccessProtocol_fk_StorageServiceId-- (is implicitly done)
-- alter table StorageShareCapacity drop constraint storageShareCapacity_fk_StorageShareId-- (is implicitly done)
-- alter table DomainContact drop constraint domainContact_fk_DomainId-- (is implicitly done)
-- alter table DomainContact drop constraint domainContact_fk_ContactId-- (is implicitly done)
-- alter table AdminDomain drop constraint adminDomain_fk_AdminDomainId-- (is implicitly done)
-- alter table UserDomain drop constraint userDomain_fk_UserDomainId-- (is implicitly done)
-- alter table Service drop constraint service_fk_AdminDomainId-- (is implicitly done)
-- alter table UserDomainPolicy drop constraint userDomainPolicy_fk_UserDomainId-- (is implicitly done)
-- alter table UserDomainPolicy drop constraint userDomainPolicy_fk_PolicyId-- (is implicitly done)
-- alter table Service drop constraint service_fk_LocationId-- (is implicitly done)
-- alter table ServiceContact drop constraint serviceContact_fk_ServiceId-- (is implicitly done)
-- alter table ServiceContact drop constraint serviceContact_fk_ContactId-- (is implicitly done)
-- alter table Domain drop constraint domain_fk_LocationId-- (is implicitly done)
-- alter table ServiceService drop constraint serviceService_fk_ServiceId-- (is implicitly done)
-- alter table ServiceService drop constraint serviceService_fk_ServiceId-- (is implicitly done)
-- alter table Endpoint drop constraint endpoint_fk_ServiceId-- (is implicitly done)
-- alter table AccessPolicy drop constraint accessPolicy_fk_EndpointId-- (is implicitly done)
-- alter table Activity drop constraint activity_fk_EndpointId-- (is implicitly done)
-- alter table ActivityActivity drop constraint activityActivity_fk_ActivityId-- (is implicitly done)
-- alter table ActivityActivity drop constraint activityActivity_fk_ActivityId-- (is implicitly done)
-- alter table Activity drop constraint activity_fk_UserDomainId-- (is implicitly done)
-- alter table Manager drop constraint manager_fk_ServiceId-- (is implicitly done)
-- alter table Share drop constraint share_fk_ServiceId-- (is implicitly done)
-- alter table ShareEndpoint drop constraint shareEndpoint_fk_ShareId-- (is implicitly done)
-- alter table ShareEndpoint drop constraint shareEndpoint_fk_EndpointId-- (is implicitly done)
-- alter table ResourceShare drop constraint resourceShare_fk_ResourceId-- (is implicitly done)
-- alter table ResourceShare drop constraint resourceShare_fk_ShareId-- (is implicitly done)
-- alter table Activity drop constraint activity_fk_ShareId-- (is implicitly done)
-- alter table MappingPolicy drop constraint mappingPolicy_fk_ShareId-- (is implicitly done)
-- alter table Resource drop constraint resource_fk_ManagerId-- (is implicitly done)
-- alter table Activity drop constraint activity_fk_ResourceId-- (is implicitly done)
-- alter table StorageService drop constraint storageService_fk_Id-- (is implicitly done)
-- alter table StorageEndpoint drop constraint storageEndpoint_fk_Id-- (is implicitly done)
-- alter table StorageShare drop constraint storageShare_fk_Id-- (is implicitly done)
-- alter table DataStore drop constraint dataStore_fk_Id-- (is implicitly done)
-- alter table StorageManager drop constraint storageManager_fk_Id-- (is implicitly done)
-- alter table StorageShare_MVA drop constraint storageShare_MVA_fk_Id-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia

 drop table if exists ExecutionEnvironmentApplicationEnvironment ;
 drop table if exists DomainContact ;
 drop table if exists UserDomainPolicy ;
 drop table if exists ServiceContact ;
 drop table if exists ServiceService ;
 drop table if exists ActivityActivity ;
 drop table if exists ShareEndpoint ;
 drop table if exists ResourceShare ;
 drop table if exists ComputingManager ;
 drop table if exists ComputingShare ;
 drop table if exists ComputingService ;
 drop table if exists ComputingEndpoint ;
 drop table if exists Benchmark ;
 drop table if exists ApplicationEnvironment ;
 drop table if exists ToStorageService ;
 drop table if exists ComputingActivity ;
 drop table if exists ApplicationHandle ;
 drop table if exists ExecutionEnvironment ;
 drop table if exists ComputingEndpoint_MVA ;
 drop table if exists ComputingManager_MVA ;
 drop table if exists ExecutionEnvironment_MVA ;
 drop table if exists ApplicationEnvironment_MVA ;
 drop table if exists ComputingActivity_MVA ;
 drop table if exists ComputingShare_MVA ;
 drop table if exists Location ;
 drop table if exists Activity ;
 drop table if exists AdminDomain ;
 drop table if exists Contact ;
 drop table if exists Service ;
 drop table if exists Endpoint ;
 drop table if exists AccessPolicy ;
 drop table if exists UserDomain ;
 drop table if exists MappingPolicy ;
 drop table if exists Domain ;
 drop table if exists Policy ;
 drop table if exists Share ;
 drop table if exists Manager ;
 drop table if exists Resource ;
 drop table if exists Domain_MVA ;
 drop table if exists AdminDomain_MVA ;
 drop table if exists UserDomain_MVA ;
 drop table if exists Service_MVA ;
 drop table if exists Endpoint_MVA ;
 drop table if exists Policy_MVA ;
 drop table if exists Extension ;
 drop table if exists StorageService ;
 drop table if exists StorageServiceCapacity ;
 drop table if exists StorageAccessProtocol ;
 drop table if exists StorageEndpoint ;
 drop table if exists StorageShare ;
 drop table if exists StorageShareCapacity ;
 drop table if exists StorageManager ;
 drop table if exists DataStore ;
 drop table if exists ToComputingService ;
 drop table if exists StorageShare_MVA ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia


-- ExecutionEnvironmentApplicationEnvironment
-- Association between ExecutionEnvironment and ApplicationEnvironment
create table ExecutionEnvironmentApplicationEnvironment (
  executionEnvironmentId    varchar(255) not null,
  applicationEnvironmentId  varchar(255) not null,
  constraint pk_ExecutionEnvironmentApplicationEnvironment primary key (executionEnvironmentId,applicationEnvironmentId)
) type = InnoDB ;

-- DomainContact
-- Association between Domain and Contact
create table DomainContact (
  domainId                  varchar(255) not null,
  contactId                 varchar(255) not null,
  constraint pk_DomainContact primary key (domainId,contactId)
) type = InnoDB ;

-- UserDomainPolicy
-- Association between UserDomain and Policy
create table UserDomainPolicy (
  userDomainId              varchar(255) not null,
  policyId                  varchar(255) not null,
  constraint pk_UserDomainPolicy primary key (userDomainId,policyId)
) type = InnoDB ;

-- ServiceContact
-- Association between Service and Contact
create table ServiceContact (
  serviceId                 varchar(255) not null,
  contactId                 varchar(255) not null,
  constraint pk_ServiceContact primary key (serviceId,contactId)
) type = InnoDB ;

-- ServiceService
-- Association between Service and Service
create table ServiceService (
  serviceId2                varchar(255) not null,
  serviceId1                varchar(255) not null,
  constraint pk_ServiceService primary key (serviceId2,serviceId1)
) type = InnoDB ;

-- ActivityActivity
-- Association between Activity and Activity
create table ActivityActivity (
  activityId2               varchar(255) not null,
  activityId1               varchar(255) not null,
  constraint pk_ActivityActivity primary key (activityId2,activityId1)
) type = InnoDB ;

-- ShareEndpoint
-- Association between Share and Endpoint
create table ShareEndpoint (
  shareId                   varchar(255) not null,
  endpointId                varchar(255) not null,
  constraint pk_ShareEndpoint primary key (shareId,endpointId)
) type = InnoDB ;

-- ResourceShare
-- Association between Resource and Share
create table ResourceShare (
  resourceId                varchar(255) not null,
  shareId                   varchar(255) not null,
  constraint pk_ResourceShare primary key (resourceId,shareId)
) type = InnoDB ;

-- ComputingManager
create table ComputingManager (
  Id                        varchar(255) not null,
  Reservation               varchar(255),
  BulkSubmission            varchar(255),
  TotalPhysicalCPUs         integer,
  TotalLogicalCPUs          integer,
  TotalSlots                integer,
  SlotsUsedByLocalJobs      integer,
  SlotsUsedByGridJobs       integer,
  Homogeneous               varchar(255),
  LogicalCPUDistribution    varchar(255),
  WorkingAreaShared         varchar(255),
  WorkingAreaGuaranteed     varchar(255),
  WorkingAreaTotal          integer,
  WorkingAreaFree           integer,
  WorkingAreaLifeTime       integer,
  WorkingAreaMultiSlotTotal integer,
  WorkingAreaMultiSlotFree  integer,
  WorkingAreaMultiSlotLifeTime integer,
  CacheTotal                integer,
  CacheFree                 integer,
  TmpDir                    varchar(255),
  ScratchDir                varchar(255),
  ApplicationDir            varchar(255),
  constraint pk_ComputingManager primary key (Id)
) type = InnoDB ;

-- ComputingShare
create table ComputingShare (
  Id                        varchar(255) not null,
  MappingQueue              varchar(255),
  MaxWallTime               integer,
  MaxMultiSlotWallTime      integer,
  MinWallTime               integer,
  DefaultWallTime           integer,
  MaxCPUTime                integer,
  MaxTotalCPUTime           integer,
  MinCPUTime                integer,
  DefaultCPUTime            integer,
  MaxTotalJobs              integer,
  MaxRunningJobs            integer,
  MaxWaitingJobs            integer,
  MaxPreLRMSWaitingJobs     integer,
  MaxUserRunningJobs        integer,
  MaxSlotsPerJob            integer,
  MaxStageInStreams         integer,
  MaxStageOutStreams        integer,
  SchedulingPolicy          varchar(255),
  MaxMainMemory             integer,
  GuaranteedMainMemory      integer,
  MaxDiskSpace              integer,
  DefaultStorageService     varchar(255),
  Preemption                varchar(255),
  ServingState              varchar(255) not null,
  TotalJobs                 integer,
  RunningJobs               integer,
  LocalRunningJobs          integer,
  WaitingJobs               integer,
  LocalWaitingJobs          integer,
  SuspendedJobs             integer,
  LocalSuspendedJobs        integer,
  StagingJobs               integer,
  PreLRMSWaitingJobs        integer,
  EstimatedAverageWaitingTime integer,
  EstimatedWorstWaitingTime integer,
  FreeSlots                 integer,
  FreeSlotsWithDuration     varchar(255),
  UsedSlots                 integer,
  RequestedSlots            integer,
  ReservationPolicy         varchar(255),
  constraint pk_ComputingShare primary key (Id)
) type = InnoDB ;

-- ComputingService
create table ComputingService (
  Id                        varchar(255) not null,
  TotalJobs                 integer,
  RunningJobs               integer,
  WaitingJobs               integer,
  StagingJobs               integer,
  SuspendedJobs             integer,
  PreLRMSWaitingJobs        integer,
  constraint pk_ComputingService primary key (Id)
) type = InnoDB ;

-- ComputingEndpoint
create table ComputingEndpoint (
  Id                        varchar(255) not null,
  Staging                   varchar(255),
  TotalJobs                 integer,
  RunningJobs               integer,
  WaitingJobs               integer,
  StagingJobs               integer,
  SuspendedJobs             integer,
  PreLRMSWaitingJobs        integer,
  constraint pk_ComputingEndpoint primary key (Id)
) type = InnoDB ;

-- Benchmark
create table Benchmark (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  Value                     real not null,
  computingManagerId        varchar(255),
  executionEnvironmentId    varchar(255),
  constraint pk_Benchmark primary key (Id)
) type = InnoDB ;

-- ApplicationEnvironment
create table ApplicationEnvironment (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  AppName                   varchar(255) not null,
  AppVersion                varchar(255),
  Repository                varchar(255),
  State                     varchar(255),
  RemovalDate               varchar(255),
  License                   varchar(255),
  Description               varchar(255),
  ParallelSupport           varchar(255),
  MaxSlots                  integer,
  MaxJobs                   integer,
  MaxUserSeats              integer,
  FreeSlots                 integer,
  FreeJobs                  integer,
  FreeUserSeats             integer,
  computingManagerId        varchar(255) not null,
  constraint pk_ApplicationEnvironment primary key (Id)
) type = InnoDB ;

-- ToStorageService
create table ToStorageService (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  LocalPath                 varchar(255) not null,
  RemotePath                varchar(255) not null,
  computingServiceId        varchar(255) not null,
  storageServiceId          varchar(255) not null,
  constraint pk_ToStorageService primary key (Id)
) type = InnoDB ;

-- ComputingActivity
create table ComputingActivity (
  Id                        varchar(255) not null,
  Type                      varchar(255),
  IDFromEndpoint            varchar(255),
  LocalIDFromManager        varchar(255),
  JobDescription            varchar(255),
  RestartState              varchar(255),
  ExitCode                  integer,
  ComputingManagerExitCode  varchar(255),
  WaitingPosition           integer,
  UserDomain                varchar(255),
  Owner                     varchar(255),
  LocalOwner                varchar(255),
  RequestedTotalWallTime    integer,
  RequestedTotalCPUTime     integer,
  RequestedSlots            integer,
  StdIn                     varchar(255),
  StdOut                    varchar(255),
  StdErr                    varchar(255),
  LogDir                    varchar(255),
  Queue                     varchar(255),
  UsedTotalWallTime         integer,
  UsedTotalCPUTime          integer,
  UsedMainMemory            integer,
  SubmissionTime            varchar(255),
  ComputingManagerSubmissionTime varchar(255),
  StartTime                 varchar(255),
  ComputingManagerEndTime   varchar(255),
  EndTime                   varchar(255),
  WorkingAreaEraseTime      varchar(255),
  ProxyExpirationTime       varchar(255),
  SubmissionHost            varchar(255),
  SubmissionClientName      varchar(255),
  constraint pk_ComputingActivity primary key (Id)
) type = InnoDB ;

-- ApplicationHandle
create table ApplicationHandle (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  applicationEnvironmentId  varchar(255) not null,
  constraint pk_ApplicationHandle primary key (Id)
) type = InnoDB ;

-- ExecutionEnvironment
create table ExecutionEnvironment (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Platform                  varchar(255) not null,
  VirtualMachine            varchar(255),
  TotalInstances            integer,
  UsedInstances             integer,
  UnavailableInstances      integer,
  PhysicalCPUs              integer,
  LogicalCPUs               integer,
  CPUMultiplicity           varchar(255),
  CPUVendor                 varchar(255),
  CPUModel                  varchar(255),
  CPUVersion                varchar(255),
  CPUClockSpeed             integer,
  CPUTimeScalingFactor      varchar(255),
  WallTimeScalingFactor     varchar(255),
  MainMemorySize            integer,
  VirtualMemorySize         integer,
  OSFamily                  varchar(255) not null,
  OSName                    varchar(255),
  OSVersion                 varchar(255),
  ConnectivityIn            varchar(255) not null,
  ConnectivityOut           varchar(255) not null,
  NetworkInfo               varchar(255),
  constraint pk_ExecutionEnvironment primary key (Id)
) type = InnoDB ;

-- ComputingEndpoint_MVA
create table ComputingEndpoint_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingEndpoint_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- ComputingManager_MVA
create table ComputingManager_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingManager_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- ExecutionEnvironment_MVA
create table ExecutionEnvironment_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ExecutionEnvironment_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- ApplicationEnvironment_MVA
create table ApplicationEnvironment_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ApplicationEnvironment_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- ComputingActivity_MVA
create table ComputingActivity_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingActivity_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- ComputingShare_MVA
create table ComputingShare_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingShare_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- Location
create table Location (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Address                   varchar(255),
  Place                     varchar(255),
  Country                   varchar(255),
  PostCode                  varchar(255),
  Latitude                  real,
  Longitude                 real,
  constraint pk_Location primary key (Id)
) type = InnoDB ;

-- Activity
create table Activity (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  endpointId                varchar(255),
  userDomainId              varchar(255),
  shareId                   varchar(255),
  resourceId                varchar(255),
  constraint pk_Activity primary key (Id)
) type = InnoDB ;

-- AdminDomain
create table AdminDomain (
  Id                        varchar(255) not null,
  Distributed               varchar(255),
  adminDomainId             varchar(255),
  constraint pk_AdminDomain primary key (Id)
) type = InnoDB ;

-- Contact
create table Contact (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Detail                    varchar(255) not null,
  Type                      varchar(255) not null,
  constraint pk_Contact primary key (Id)
) type = InnoDB ;

-- Service
create table Service (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  QualityLevel              varchar(255) not null,
  Complexity                varchar(255),
  locationId                varchar(255),
  adminDomainId             varchar(255),
  constraint pk_Service primary key (Id)
) type = InnoDB ;

-- Endpoint
create table Endpoint (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  URL                       varchar(255) not null,
  Technology                varchar(255),
  InterfaceName             varchar(255) not null,
  Implementor               varchar(255),
  ImplementationName        varchar(255),
  ImplementationVersion     varchar(255),
  QualityLevel              varchar(255) not null,
  HealthState               varchar(255) not null,
  HealthStateInfo           varchar(255),
  ServingState              varchar(255) not null,
  StartTime                 varchar(255),
  IssuerCA                  varchar(255),
  DowntimeAnnounce          varchar(255),
  DowntimeStart             varchar(255),
  DowntimeEnd               varchar(255),
  DowntimeInfo              varchar(255),
  serviceId                 varchar(255) not null,
  constraint pk_Endpoint primary key (Id)
) type = InnoDB ;

-- AccessPolicy
create table AccessPolicy (
  Id                        varchar(255) not null,
  endpointId                varchar(255) not null,
  constraint pk_AccessPolicy primary key (Id)
) type = InnoDB ;

-- UserDomain
create table UserDomain (
  Id                        varchar(255) not null,
  Level                     integer,
  userDomainId              varchar(255),
  constraint pk_UserDomain primary key (Id)
) type = InnoDB ;

-- MappingPolicy
create table MappingPolicy (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Scheme                    varchar(255) not null,
  shareId                   varchar(255) not null,
  constraint pk_MappingPolicy primary key (Id)
) type = InnoDB ;

-- Domain
create table Domain (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Description               varchar(255),
  locationId                varchar(255),
  constraint pk_Domain primary key (Id)
) type = InnoDB ;

-- Policy
create table Policy (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Scheme                    varchar(255) not null,
  constraint pk_Policy primary key (Id)
) type = InnoDB ;

-- Share
create table Share (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Description               varchar(255),
  serviceId                 varchar(255) not null,
  constraint pk_Share primary key (Id)
) type = InnoDB ;

-- Manager
create table Manager (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  ProductName               varchar(255) not null,
  ProductVersion            varchar(255),
  serviceId                 varchar(255) not null,
  managerId                 varchar(255) not null,
  constraint pk_Manager primary key (Id)
) type = InnoDB ;

-- Resource
create table Resource (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  managerId                 varchar(255) not null,
  constraint pk_Resource primary key (Id)
) type = InnoDB ;

-- Domain_MVA
create table Domain_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Domain_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- AdminDomain_MVA
create table AdminDomain_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_AdminDomain_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- UserDomain_MVA
create table UserDomain_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_UserDomain_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- Service_MVA
create table Service_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Service_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- Endpoint_MVA
create table Endpoint_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Endpoint_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- Policy_MVA
create table Policy_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Policy_MVA primary key (Id,Type,Value)
) type = InnoDB ;

-- Extension
create table Extension (
  LocalID                   varchar(255) not null,
  `Key`                     varchar(255) not null,
  Value                     varchar(255) not null,
  applicationEnvironmentId  varchar(255),
  applicationHandleId       varchar(255),
  benchmarkId               varchar(255),
  toStorageServiceId        varchar(255),
  locationId                varchar(255),
  contactId                 varchar(255),
  serviceId                 varchar(255),
  domainId                  varchar(255),
  endpointId                varchar(255),
  shareId                   varchar(255),
  managerId                 varchar(255),
  resourceId                varchar(255),
  activityId                varchar(255),
  policyId                  varchar(255),
  storageServiceCapacityId  varchar(255),
  storageAccessProtocolId   varchar(255),
  storageShareCapacityId    varchar(255),
  toComputingServiceId      varchar(255),
  constraint pk_Extension primary key (LocalID)
) type = InnoDB ;

-- StorageService
create table StorageService (
  Id                        varchar(255) not null,
  constraint pk_StorageService primary key (Id)
) type = InnoDB ;

-- StorageServiceCapacity
create table StorageServiceCapacity (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  TotalSize                 integer,
  FreeSize                  integer,
  UsedSize                  integer,
  ReservedSize              integer,
  storageServiceId          varchar(255) not null,
  constraint pk_StorageServiceCapacity primary key (Id)
) type = InnoDB ;

-- StorageAccessProtocol
create table StorageAccessProtocol (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  Version                   varchar(255) not null,
  MaxStreams                integer,
  storageServiceId          varchar(255) not null,
  constraint pk_StorageAccessProtocol primary key (Id)
) type = InnoDB ;

-- StorageEndpoint
create table StorageEndpoint (
  Id                        varchar(255) not null,
  constraint pk_StorageEndpoint primary key (Id)
) type = InnoDB ;

-- StorageShare
create table StorageShare (
  Id                        varchar(255) not null,
  ServingState              varchar(255) not null,
  Path                      varchar(255),
  SharingID                 varchar(255) not null,
  AccessLatency             varchar(255) not null,
  DefaultLifeTime           integer,
  MaximumLifeTime           integer,
  Tag                       varchar(255),
  constraint pk_StorageShare primary key (Id)
) type = InnoDB ;

-- StorageShareCapacity
create table StorageShareCapacity (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  TotalSize                 integer,
  FreeSize                  integer,
  UsedSize                  integer,
  ReservedSize              integer,
  storageShareId            varchar(255) not null,
  constraint pk_StorageShareCapacity primary key (Id)
) type = InnoDB ;

-- StorageManager
create table StorageManager (
  Id                        varchar(255) not null,
  constraint pk_StorageManager primary key (Id)
) type = InnoDB ;

-- DataStore
create table DataStore (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Latency                   varchar(255) not null,
  TotalSize                 integer,
  FreeSize                  integer,
  UsedSize                  integer,
  constraint pk_DataStore primary key (Id)
) type = InnoDB ;

-- ToComputingService
create table ToComputingService (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  NetworkInfo               varchar(255),
  Bandwidth                 integer,
  computingServiceId        varchar(255) not null,
  storageServiceId          varchar(255) not null,
  constraint pk_ToComputingService primary key (Id)
) type = InnoDB ;

-- StorageShare_MVA
create table StorageShare_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_StorageShare_MVA primary key (Id,Type,Value)
) type = InnoDB ;

















































-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 15:48:34 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia

alter table ComputingService add constraint computingService_fk_Id
  foreign key (Id)
  references Service (Id)  ;
alter table ComputingEndpoint add constraint computingEndpoint_fk_Id
  foreign key (Id)
  references Endpoint (Id)  ;
alter table ComputingShare add constraint computingShare_fk_Id
  foreign key (Id)
  references Share (Id)  ;
alter table ComputingManager add constraint computingManager_fk_Id
  foreign key (Id)
  references Manager (Id)  ;
alter table ExecutionEnvironment add constraint executionEnvironment_fk_Id
  foreign key (Id)
  references Resource (Id)  ;
alter table ComputingActivity add constraint computingActivity_fk_Id
  foreign key (Id)
  references Activity (Id)  ;
alter table ComputingEndpoint_MVA add constraint computingEndpoint_MVA_fk_Id
  foreign key (Id)
  references ComputingEndpoint (Id)  ;
alter table ComputingManager_MVA add constraint computingManager_MVA_fk_Id
  foreign key (Id)
  references ComputingManager (Id)  ;
alter table ExecutionEnvironment_MVA add constraint executionEnvironment_MVA_fk_Id
  foreign key (Id)
  references ExecutionEnvironment (Id)  ;
alter table ApplicationEnvironment_MVA add constraint applicationEnvironment_MVA_fk_Id
  foreign key (Id)
  references ApplicationEnvironment (Id)  ;
alter table ComputingActivity_MVA add constraint computingActivity_MVA_fk_Id
  foreign key (Id)
  references ComputingActivity (Id)  ;
alter table ComputingShare_MVA add constraint computingShare_MVA_fk_Id
  foreign key (Id)
  references ComputingShare (Id)  ;
alter table AdminDomain add constraint adminDomain_fk_Id
  foreign key (Id)
  references Domain (Id)  ;
alter table UserDomain add constraint userDomain_fk_Id
  foreign key (Id)
  references Domain (Id)  ;
alter table AccessPolicy add constraint accessPolicy_fk_Id
  foreign key (Id)
  references Policy (Id)  ;
alter table MappingPolicy add constraint mappingPolicy_fk_Id
  foreign key (Id)
  references Policy (Id)  ;
alter table Domain_MVA add constraint domain_MVA_fk_Id
  foreign key (Id)
  references Domain (Id)  ;
alter table AdminDomain_MVA add constraint adminDomain_MVA_fk_Id
  foreign key (Id)
  references AdminDomain (Id)  ;
alter table UserDomain_MVA add constraint userDomain_MVA_fk_Id
  foreign key (Id)
  references UserDomain (Id)  ;
alter table Policy_MVA add constraint policy_MVA_fk_Id
  foreign key (Id)
  references Policy (Id)  ;
alter table Endpoint_MVA add constraint endpoint_MVA_fk_Id
  foreign key (Id)
  references Endpoint (Id)  ;
alter table Service_MVA add constraint service_MVA_fk_Id
  foreign key (Id)
  references Service (Id)  ;
alter table Extension add constraint extension_fk_ApplicationEnvironmentId
  foreign key (applicationEnvironmentId)
  references ApplicationEnvironment (Id)  ;
alter table Extension add constraint extension_fk_ApplicationHandleId
  foreign key (applicationHandleId)
  references ApplicationHandle (Id)  ;
alter table Extension add constraint extension_fk_BenchmarkId
  foreign key (benchmarkId)
  references Benchmark (Id)  ;
alter table Extension add constraint extension_fk_ToStorageServiceId
  foreign key (toStorageServiceId)
  references ToStorageService (Id)  ;
alter table Extension add constraint extension_fk_StorageServiceCapacityId
  foreign key (storageServiceCapacityId)
  references StorageServiceCapacity (Id)  ;
alter table Extension add constraint extension_fk_StorageAccessProtocolId
  foreign key (storageAccessProtocolId)
  references StorageAccessProtocol (Id)  ;
alter table Extension add constraint extension_fk_StorageShareCapacityId
  foreign key (storageShareCapacityId)
  references StorageShareCapacity (Id)  ;
alter table Extension add constraint extension_fk_ToComputingServiceId
  foreign key (toComputingServiceId)
  references ToComputingService (Id)  ;
alter table Extension add constraint extension_fk_LocationId
  foreign key (locationId)
  references Location (Id)  ;
alter table Extension add constraint extension_fk_ContactId
  foreign key (contactId)
  references Contact (Id)  ;
alter table Extension add constraint extension_fk_ServiceId
  foreign key (serviceId)
  references Service (Id)  ;
alter table Extension add constraint extension_fk_DomainId
  foreign key (domainId)
  references Domain (Id)  ;
alter table Extension add constraint extension_fk_EndpointId
  foreign key (endpointId)
  references Endpoint (Id)  ;
alter table Extension add constraint extension_fk_ShareId
  foreign key (shareId)
  references Share (Id)  ;
alter table Extension add constraint extension_fk_ManagerId
  foreign key (managerId)
  references Manager (Id)  ;
alter table Extension add constraint extension_fk_ResourceId
  foreign key (resourceId)
  references Resource (Id)  ;
alter table Extension add constraint extension_fk_ActivityId
  foreign key (activityId)
  references Activity (Id)  ;
alter table Extension add constraint extension_fk_PolicyId
  foreign key (policyId)
  references Policy (Id)  ;
alter table ToComputingService add constraint toComputingService_fk_ComputingServiceId
  foreign key (computingServiceId)
  references ComputingService (Id)  ;
alter table ToStorageService add constraint toStorageService_fk_ComputingServiceId
  foreign key (computingServiceId)
  references ComputingService (Id)  ;
alter table ApplicationEnvironment add constraint applicationEnvironment_fk_ComputingManagerId
  foreign key (computingManagerId)
  references ComputingManager (Id)  ;
alter table Benchmark add constraint benchmark_fk_ComputingManagerId
  foreign key (computingManagerId)
  references ComputingManager (Id)  ;
alter table Benchmark add constraint benchmark_fk_ExecutionEnvironmentId
  foreign key (executionEnvironmentId)
  references ExecutionEnvironment (Id)  ;
alter table ExecutionEnvironmentApplicationEnvironment add constraint exctnvrnmntplctnvrnmnt_fk_ExecutionEnvironmentId
  foreign key (executionEnvironmentId)
  references ExecutionEnvironment (Id) on delete cascade ;
alter table ExecutionEnvironmentApplicationEnvironment add constraint exctnvrnmntplctnvrnmnt_fk_ApplicationEnvironmentId
  foreign key (applicationEnvironmentId)
  references ApplicationEnvironment (Id) on delete cascade ;
alter table ApplicationHandle add constraint applicationHandle_fk_ApplicationEnvironmentId
  foreign key (applicationEnvironmentId)
  references ApplicationEnvironment (Id)  ;
alter table ToStorageService add constraint toStorageService_fk_StorageServiceId
  foreign key (storageServiceId)
  references StorageService (Id)  ;
alter table ToComputingService add constraint toComputingService_fk_StorageServiceId
  foreign key (storageServiceId)
  references StorageService (Id)  ;
alter table StorageServiceCapacity add constraint storageServiceCapacity_fk_StorageServiceId
  foreign key (storageServiceId)
  references StorageService (Id)  ;
alter table StorageAccessProtocol add constraint storageAccessProtocol_fk_StorageServiceId
  foreign key (storageServiceId)
  references StorageService (Id)  ;
alter table StorageShareCapacity add constraint storageShareCapacity_fk_StorageShareId
  foreign key (storageShareId)
  references StorageShare (Id)  ;
alter table DomainContact add constraint domainContact_fk_DomainId
  foreign key (domainId)
  references Domain (Id) on delete cascade ;
alter table DomainContact add constraint domainContact_fk_ContactId
  foreign key (contactId)
  references Contact (Id) on delete cascade ;
alter table AdminDomain add constraint adminDomain_fk_AdminDomainId
  foreign key (adminDomainId)
  references AdminDomain (Id)  ;
alter table UserDomain add constraint userDomain_fk_UserDomainId
  foreign key (userDomainId)
  references UserDomain (Id)  ;
alter table Service add constraint service_fk_AdminDomainId
  foreign key (adminDomainId)
  references AdminDomain (Id)  ;
alter table UserDomainPolicy add constraint userDomainPolicy_fk_UserDomainId
  foreign key (userDomainId)
  references UserDomain (Id) on delete cascade ;
alter table UserDomainPolicy add constraint userDomainPolicy_fk_PolicyId
  foreign key (policyId)
  references Policy (Id) on delete cascade ;
alter table Service add constraint service_fk_LocationId
  foreign key (locationId)
  references Location (Id)  ;
alter table ServiceContact add constraint serviceContact_fk_ServiceId
  foreign key (serviceId)
  references Service (Id) on delete cascade ;
alter table ServiceContact add constraint serviceContact_fk_ContactId
  foreign key (contactId)
  references Contact (Id) on delete cascade ;
alter table Domain add constraint domain_fk_LocationId
  foreign key (locationId)
  references Location (Id)  ;
alter table ServiceService add constraint serviceService_fk_ServiceId
  foreign key (serviceId2)
  references Service (Id) on delete cascade ;
alter table ServiceService add constraint serviceService_fk_ServiceId
  foreign key (serviceId1)
  references Service (Id) on delete cascade ;
alter table Endpoint add constraint endpoint_fk_ServiceId
  foreign key (serviceId)
  references Service (Id)  ;
alter table AccessPolicy add constraint accessPolicy_fk_EndpointId
  foreign key (endpointId)
  references Endpoint (Id)  ;
alter table Activity add constraint activity_fk_EndpointId
  foreign key (endpointId)
  references Endpoint (Id)  ;
alter table ActivityActivity add constraint activityActivity_fk_ActivityId
  foreign key (activityId2)
  references Activity (Id) on delete cascade ;
alter table ActivityActivity add constraint activityActivity_fk_ActivityId
  foreign key (activityId1)
  references Activity (Id) on delete cascade ;
alter table Activity add constraint activity_fk_UserDomainId
  foreign key (userDomainId)
  references UserDomain (Id)  ;
alter table Manager add constraint manager_fk_ServiceId
  foreign key (serviceId)
  references Service (Id)  ;
alter table Share add constraint share_fk_ServiceId
  foreign key (serviceId)
  references Service (Id)  ;
alter table ShareEndpoint add constraint shareEndpoint_fk_ShareId
  foreign key (shareId)
  references Share (Id) on delete cascade ;
alter table ShareEndpoint add constraint shareEndpoint_fk_EndpointId
  foreign key (endpointId)
  references Endpoint (Id) on delete cascade ;
alter table ResourceShare add constraint resourceShare_fk_ResourceId
  foreign key (resourceId)
  references Resource (Id) on delete cascade ;
alter table ResourceShare add constraint resourceShare_fk_ShareId
  foreign key (shareId)
  references Share (Id) on delete cascade ;
alter table Activity add constraint activity_fk_ShareId
  foreign key (shareId)
  references Share (Id)  ;
alter table MappingPolicy add constraint mappingPolicy_fk_ShareId
  foreign key (shareId)
  references Share (Id)  ;
alter table Resource add constraint resource_fk_ManagerId
  foreign key (managerId)
  references Manager (Id)  ;
alter table Activity add constraint activity_fk_ResourceId
  foreign key (resourceId)
  references Resource (Id)  ;
alter table StorageService add constraint storageService_fk_Id
  foreign key (Id)
  references Service (Id)  ;
alter table StorageEndpoint add constraint storageEndpoint_fk_Id
  foreign key (Id)
  references Endpoint (Id)  ;
alter table StorageShare add constraint storageShare_fk_Id
  foreign key (Id)
  references Share (Id)  ;
alter table DataStore add constraint dataStore_fk_Id
  foreign key (Id)
  references Resource (Id)  ;
alter table StorageManager add constraint storageManager_fk_Id
  foreign key (Id)
  references Manager (Id)  ;
alter table StorageShare_MVA add constraint storageShare_MVA_fk_Id
  foreign key (Id)
  references StorageShare (Id)  ;

-- innodb requires a special 'quit' command
commit ;

