-- ================================================================================
--   mysql SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   mysql
--   Generated at:      Thu Apr 23 13:21:16 2009
--   Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia

-- drop constraint computingService_fk_Id for mysql
-- drop constraint computingEndpoint_fk_Id for mysql
-- drop constraint computingShare_fk_Id for mysql
-- drop constraint computingManager_fk_Id for mysql
-- drop constraint executionEnvironment_fk_Id for mysql
-- drop constraint computingActivity_fk_Id for mysql
-- drop constraint computingEndpoint_MVA_fk_Id for mysql
-- drop constraint computingManager_MVA_fk_Id for mysql
-- drop constraint executionEnvironment_MVA_fk_Id for mysql
-- drop constraint applicationEnvironment_MVA_fk_Id for mysql
-- drop constraint computingActivity_MVA_fk_Id for mysql
-- drop constraint computingShare_MVA_fk_Id for mysql
-- drop constraint adminDomain_fk_Id for mysql
-- drop constraint userDomain_fk_Id for mysql
-- drop constraint accessPolicy_fk_Id for mysql
-- drop constraint mappingPolicy_fk_Id for mysql
-- drop constraint domain_MVA_fk_Id for mysql
-- drop constraint adminDomain_MVA_fk_Id for mysql
-- drop constraint userDomain_MVA_fk_Id for mysql
-- drop constraint policy_MVA_fk_Id for mysql
-- drop constraint endpoint_MVA_fk_Id for mysql
-- drop constraint service_MVA_fk_Id for mysql
-- drop constraint extension_fk_ApplicationEnvironmentId for mysql
-- drop constraint extension_fk_ApplicationHandleId for mysql
-- drop constraint extension_fk_BenchmarkId for mysql
-- drop constraint extension_fk_ToStorageServiceId for mysql
-- drop constraint extension_fk_StorageServiceCapacityId for mysql
-- drop constraint extension_fk_StorageAccessProtocolId for mysql
-- drop constraint extension_fk_StorageShareCapacityId for mysql
-- drop constraint extension_fk_ToComputingServiceId for mysql
-- drop constraint extension_fk_LocationId for mysql
-- drop constraint extension_fk_ContactId for mysql
-- drop constraint extension_fk_ServiceId for mysql
-- drop constraint extension_fk_DomainId for mysql
-- drop constraint extension_fk_EndpointId for mysql
-- drop constraint extension_fk_ShareId for mysql
-- drop constraint extension_fk_ManagerId for mysql
-- drop constraint extension_fk_ResourceId for mysql
-- drop constraint extension_fk_ActivityId for mysql
-- drop constraint extension_fk_PolicyId for mysql
-- drop constraint toComputingService_fk_ComputingServiceId for mysql
-- drop constraint toStorageService_fk_ComputingServiceId for mysql
-- drop constraint applicationEnvironment_fk_ComputingManagerId for mysql
-- drop constraint benchmark_fk_ComputingManagerId for mysql
-- drop constraint benchmark_fk_ExecutionEnvironmentId for mysql
-- drop constraint exctnvrnmntplctnvrnmnt_fk_ExecutionEnvironmentId for mysql
-- drop constraint exctnvrnmntplctnvrnmnt_fk_ApplicationEnvironmentId for mysql
-- drop constraint applicationHandle_fk_ApplicationEnvironmentId for mysql
-- drop constraint toStorageService_fk_StorageServiceId for mysql
-- drop constraint toComputingService_fk_StorageServiceId for mysql
-- drop constraint storageServiceCapacity_fk_StorageServiceId for mysql
-- drop constraint storageAccessProtocol_fk_StorageServiceId for mysql
-- drop constraint storageShareCapacity_fk_StorageShareId for mysql
-- drop constraint domainContact_fk_DomainId for mysql
-- drop constraint domainContact_fk_ContactId for mysql
-- drop constraint adminDomain_fk_AdminDomainId for mysql
-- drop constraint userDomain_fk_UserDomainId for mysql
-- drop constraint service_fk_AdminDomainId for mysql
-- drop constraint userDomainPolicy_fk_UserDomainId for mysql
-- drop constraint userDomainPolicy_fk_PolicyId for mysql
-- drop constraint service_fk_LocationId for mysql
-- drop constraint serviceContact_fk_ServiceId for mysql
-- drop constraint serviceContact_fk_ContactId for mysql
-- drop constraint domain_fk_LocationId for mysql
-- drop constraint serviceService_fk_ServiceId for mysql
-- drop constraint serviceService_fk_ServiceId for mysql
-- drop constraint endpoint_fk_ServiceId for mysql
-- drop constraint accessPolicy_fk_EndpointId for mysql
-- drop constraint activity_fk_EndpointId for mysql
-- drop constraint activityActivity_fk_ActivityId for mysql
-- drop constraint activityActivity_fk_ActivityId for mysql
-- drop constraint activity_fk_UserDomainId for mysql
-- drop constraint manager_fk_ServiceId for mysql
-- drop constraint share_fk_ServiceId for mysql
-- drop constraint shareEndpoint_fk_ShareId for mysql
-- drop constraint shareEndpoint_fk_EndpointId for mysql
-- drop constraint resourceShare_fk_ResourceId for mysql
-- drop constraint resourceShare_fk_ShareId for mysql
-- drop constraint activity_fk_ShareId for mysql
-- drop constraint mappingPolicy_fk_ShareId for mysql
-- drop constraint resource_fk_ManagerId for mysql
-- drop constraint activity_fk_ResourceId for mysql
-- drop constraint storageService_fk_Id for mysql
-- drop constraint storageEndpoint_fk_Id for mysql
-- drop constraint storageShare_fk_Id for mysql
-- drop constraint dataStore_fk_Id for mysql
-- drop constraint storageManager_fk_Id for mysql
-- drop constraint storageShare_MVA_fk_Id for mysql


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia

 drop table if exists ExecutionEnvironmentApplicationEnvironment ;
 drop table if exists DomainContact ;
 drop table if exists UserDomainPolicy ;
 drop table if exists ServiceContact ;
 drop table if exists ServiceService ;
 drop table if exists ActivityActivity ;
 drop table if exists ShareEndpoint ;
 drop table if exists ResourceShare ;
 drop table if exists ComputingManager ;
 drop table if exists ComputingShare ;
 drop table if exists ComputingService ;
 drop table if exists ComputingEndpoint ;
 drop table if exists Benchmark ;
 drop table if exists ApplicationEnvironment ;
 drop table if exists ToStorageService ;
 drop table if exists ComputingActivity ;
 drop table if exists ApplicationHandle ;
 drop table if exists ExecutionEnvironment ;
 drop table if exists ComputingEndpoint_MVA ;
 drop table if exists ComputingManager_MVA ;
 drop table if exists ExecutionEnvironment_MVA ;
 drop table if exists ApplicationEnvironment_MVA ;
 drop table if exists ComputingActivity_MVA ;
 drop table if exists ComputingShare_MVA ;
 drop table if exists Location ;
 drop table if exists Activity ;
 drop table if exists AdminDomain ;
 drop table if exists Contact ;
 drop table if exists Service ;
 drop table if exists Endpoint ;
 drop table if exists AccessPolicy ;
 drop table if exists UserDomain ;
 drop table if exists MappingPolicy ;
 drop table if exists Domain ;
 drop table if exists Policy ;
 drop table if exists Share ;
 drop table if exists Manager ;
 drop table if exists Resource ;
 drop table if exists Domain_MVA ;
 drop table if exists AdminDomain_MVA ;
 drop table if exists UserDomain_MVA ;
 drop table if exists Service_MVA ;
 drop table if exists Endpoint_MVA ;
 drop table if exists Policy_MVA ;
 drop table if exists Extension ;
 drop table if exists StorageService ;
 drop table if exists StorageServiceCapacity ;
 drop table if exists StorageAccessProtocol ;
 drop table if exists StorageEndpoint ;
 drop table if exists StorageShare ;
 drop table if exists StorageShareCapacity ;
 drop table if exists StorageManager ;
 drop table if exists DataStore ;
 drop table if exists ToComputingService ;
 drop table if exists StorageShare_MVA ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia


-- ExecutionEnvironmentApplicationEnvironment
-- Association between ExecutionEnvironment and ApplicationEnvironment
create table ExecutionEnvironmentApplicationEnvironment (
  executionEnvironmentId    varchar(255) not null,
  applicationEnvironmentId  varchar(255) not null,
  constraint pk_ExecutionEnvironmentApplicationEnvironment primary key (executionEnvironmentId,applicationEnvironmentId)
) ;

-- DomainContact
-- Association between Domain and Contact
create table DomainContact (
  domainId                  varchar(255) not null,
  contactId                 varchar(255) not null,
  constraint pk_DomainContact primary key (domainId,contactId)
) ;

-- UserDomainPolicy
-- Association between UserDomain and Policy
create table UserDomainPolicy (
  userDomainId              varchar(255) not null,
  policyId                  varchar(255) not null,
  constraint pk_UserDomainPolicy primary key (userDomainId,policyId)
) ;

-- ServiceContact
-- Association between Service and Contact
create table ServiceContact (
  serviceId                 varchar(255) not null,
  contactId                 varchar(255) not null,
  constraint pk_ServiceContact primary key (serviceId,contactId)
) ;

-- ServiceService
-- Association between Service and Service
create table ServiceService (
  serviceId2                varchar(255) not null,
  serviceId1                varchar(255) not null,
  constraint pk_ServiceService primary key (serviceId2,serviceId1)
) ;

-- ActivityActivity
-- Association between Activity and Activity
create table ActivityActivity (
  activityId2               varchar(255) not null,
  activityId1               varchar(255) not null,
  constraint pk_ActivityActivity primary key (activityId2,activityId1)
) ;

-- ShareEndpoint
-- Association between Share and Endpoint
create table ShareEndpoint (
  shareId                   varchar(255) not null,
  endpointId                varchar(255) not null,
  constraint pk_ShareEndpoint primary key (shareId,endpointId)
) ;

-- ResourceShare
-- Association between Resource and Share
create table ResourceShare (
  resourceId                varchar(255) not null,
  shareId                   varchar(255) not null,
  constraint pk_ResourceShare primary key (resourceId,shareId)
) ;

-- ComputingManager
create table ComputingManager (
  Id                        varchar(255) not null,
  Reservation               varchar(255),
  BulkSubmission            varchar(255),
  TotalPhysicalCPUs         integer,
  TotalLogicalCPUs          integer,
  TotalSlots                integer,
  SlotsUsedByLocalJobs      integer,
  SlotsUsedByGridJobs       integer,
  Homogeneous               varchar(255),
  LogicalCPUDistribution    varchar(255),
  WorkingAreaShared         varchar(255),
  WorkingAreaGuaranteed     varchar(255),
  WorkingAreaTotal          integer,
  WorkingAreaFree           integer,
  WorkingAreaLifeTime       integer,
  WorkingAreaMultiSlotTotal integer,
  WorkingAreaMultiSlotFree  integer,
  WorkingAreaMultiSlotLifeTime integer,
  CacheTotal                integer,
  CacheFree                 integer,
  TmpDir                    varchar(255),
  ScratchDir                varchar(255),
  ApplicationDir            varchar(255),
  constraint pk_ComputingManager primary key (Id)
) ;

-- ComputingShare
create table ComputingShare (
  Id                        varchar(255) not null,
  MappingQueue              varchar(255),
  MaxWallTime               integer,
  MaxMultiSlotWallTime      integer,
  MinWallTime               integer,
  DefaultWallTime           integer,
  MaxCPUTime                integer,
  MaxTotalCPUTime           integer,
  MinCPUTime                integer,
  DefaultCPUTime            integer,
  MaxTotalJobs              integer,
  MaxRunningJobs            integer,
  MaxWaitingJobs            integer,
  MaxPreLRMSWaitingJobs     integer,
  MaxUserRunningJobs        integer,
  MaxSlotsPerJob            integer,
  MaxStageInStreams         integer,
  MaxStageOutStreams        integer,
  SchedulingPolicy          varchar(255),
  MaxMainMemory             integer,
  GuaranteedMainMemory      integer,
  MaxDiskSpace              integer,
  DefaultStorageService     varchar(255),
  Preemption                varchar(255),
  ServingState              varchar(255) not null,
  TotalJobs                 integer,
  RunningJobs               integer,
  LocalRunningJobs          integer,
  WaitingJobs               integer,
  LocalWaitingJobs          integer,
  SuspendedJobs             integer,
  LocalSuspendedJobs        integer,
  StagingJobs               integer,
  PreLRMSWaitingJobs        integer,
  EstimatedAverageWaitingTime integer,
  EstimatedWorstWaitingTime integer,
  FreeSlots                 integer,
  FreeSlotsWithDuration     varchar(255),
  UsedSlots                 integer,
  RequestedSlots            integer,
  ReservationPolicy         varchar(255),
  constraint pk_ComputingShare primary key (Id)
) ;

-- ComputingService
create table ComputingService (
  Id                        varchar(255) not null,
  TotalJobs                 integer,
  RunningJobs               integer,
  WaitingJobs               integer,
  StagingJobs               integer,
  SuspendedJobs             integer,
  PreLRMSWaitingJobs        integer,
  constraint pk_ComputingService primary key (Id)
) ;

-- ComputingEndpoint
create table ComputingEndpoint (
  Id                        varchar(255) not null,
  Staging                   varchar(255),
  TotalJobs                 integer,
  RunningJobs               integer,
  WaitingJobs               integer,
  StagingJobs               integer,
  SuspendedJobs             integer,
  PreLRMSWaitingJobs        integer,
  constraint pk_ComputingEndpoint primary key (Id)
) ;

-- Benchmark
create table Benchmark (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  Value                     real not null,
  computingManagerId        varchar(255),
  executionEnvironmentId    varchar(255),
  constraint pk_Benchmark primary key (Id)
) ;

-- ApplicationEnvironment
create table ApplicationEnvironment (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  AppName                   varchar(255) not null,
  AppVersion                varchar(255),
  Repository                varchar(255),
  State                     varchar(255),
  RemovalDate               varchar(255),
  License                   varchar(255),
  Description               varchar(255),
  ParallelSupport           varchar(255),
  MaxSlots                  integer,
  MaxJobs                   integer,
  MaxUserSeats              integer,
  FreeSlots                 integer,
  FreeJobs                  integer,
  FreeUserSeats             integer,
  computingManagerId        varchar(255) not null,
  constraint pk_ApplicationEnvironment primary key (Id)
) ;

-- ToStorageService
create table ToStorageService (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  LocalPath                 varchar(255) not null,
  RemotePath                varchar(255) not null,
  computingServiceId        varchar(255) not null,
  storageServiceId          varchar(255) not null,
  constraint pk_ToStorageService primary key (Id)
) ;

-- ComputingActivity
create table ComputingActivity (
  Id                        varchar(255) not null,
  Type                      varchar(255),
  IDFromEndpoint            varchar(255),
  LocalIDFromManager        varchar(255),
  JobDescription            varchar(255),
  RestartState              varchar(255),
  ExitCode                  integer,
  ComputingManagerExitCode  varchar(255),
  WaitingPosition           integer,
  UserDomain                varchar(255),
  Owner                     varchar(255),
  LocalOwner                varchar(255),
  RequestedTotalWallTime    integer,
  RequestedTotalCPUTime     integer,
  RequestedSlots            integer,
  StdIn                     varchar(255),
  StdOut                    varchar(255),
  StdErr                    varchar(255),
  LogDir                    varchar(255),
  Queue                     varchar(255),
  UsedTotalWallTime         integer,
  UsedTotalCPUTime          integer,
  UsedMainMemory            integer,
  SubmissionTime            varchar(255),
  ComputingManagerSubmissionTime varchar(255),
  StartTime                 varchar(255),
  ComputingManagerEndTime   varchar(255),
  EndTime                   varchar(255),
  WorkingAreaEraseTime      varchar(255),
  ProxyExpirationTime       varchar(255),
  SubmissionHost            varchar(255),
  SubmissionClientName      varchar(255),
  constraint pk_ComputingActivity primary key (Id)
) ;

-- ApplicationHandle
create table ApplicationHandle (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  applicationEnvironmentId  varchar(255) not null,
  constraint pk_ApplicationHandle primary key (Id)
) ;

-- ExecutionEnvironment
create table ExecutionEnvironment (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Platform                  varchar(255) not null,
  VirtualMachine            varchar(255),
  TotalInstances            integer,
  UsedInstances             integer,
  UnavailableInstances      integer,
  PhysicalCPUs              integer,
  LogicalCPUs               integer,
  CPUMultiplicity           varchar(255),
  CPUVendor                 varchar(255),
  CPUModel                  varchar(255),
  CPUVersion                varchar(255),
  CPUClockSpeed             integer,
  CPUTimeScalingFactor      varchar(255),
  WallTimeScalingFactor     varchar(255),
  MainMemorySize            integer,
  VirtualMemorySize         integer,
  OSFamily                  varchar(255) not null,
  OSName                    varchar(255),
  OSVersion                 varchar(255),
  ConnectivityIn            varchar(255) not null,
  ConnectivityOut           varchar(255) not null,
  NetworkInfo               varchar(255),
  constraint pk_ExecutionEnvironment primary key (Id)
) ;

-- ComputingEndpoint_MVA
create table ComputingEndpoint_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingEndpoint_MVA primary key (Id,Type,Value)
) ;

-- ComputingManager_MVA
create table ComputingManager_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingManager_MVA primary key (Id,Type,Value)
) ;

-- ExecutionEnvironment_MVA
create table ExecutionEnvironment_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ExecutionEnvironment_MVA primary key (Id,Type,Value)
) ;

-- ApplicationEnvironment_MVA
create table ApplicationEnvironment_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ApplicationEnvironment_MVA primary key (Id,Type,Value)
) ;

-- ComputingActivity_MVA
create table ComputingActivity_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingActivity_MVA primary key (Id,Type,Value)
) ;

-- ComputingShare_MVA
create table ComputingShare_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_ComputingShare_MVA primary key (Id,Type,Value)
) ;

-- Location
create table Location (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Address                   varchar(255),
  Place                     varchar(255),
  Country                   varchar(255),
  PostCode                  varchar(255),
  Latitude                  real,
  Longitude                 real,
  constraint pk_Location primary key (Id)
) ;

-- Activity
create table Activity (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  endpointId                varchar(255),
  userDomainId              varchar(255),
  shareId                   varchar(255),
  resourceId                varchar(255),
  constraint pk_Activity primary key (Id)
) ;

-- AdminDomain
create table AdminDomain (
  Id                        varchar(255) not null,
  Distributed               varchar(255),
  adminDomainId             varchar(255),
  constraint pk_AdminDomain primary key (Id)
) ;

-- Contact
create table Contact (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Detail                    varchar(255) not null,
  Type                      varchar(255) not null,
  constraint pk_Contact primary key (Id)
) ;

-- Service
create table Service (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  QualityLevel              varchar(255) not null,
  Complexity                varchar(255),
  locationId                varchar(255),
  adminDomainId             varchar(255),
  constraint pk_Service primary key (Id)
) ;

-- Endpoint
create table Endpoint (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  URL                       varchar(255) not null,
  Technology                varchar(255),
  InterfaceName             varchar(255) not null,
  Implementor               varchar(255),
  ImplementationName        varchar(255),
  ImplementationVersion     varchar(255),
  QualityLevel              varchar(255) not null,
  HealthState               varchar(255) not null,
  HealthStateInfo           varchar(255),
  ServingState              varchar(255) not null,
  StartTime                 varchar(255),
  IssuerCA                  varchar(255),
  DowntimeAnnounce          varchar(255),
  DowntimeStart             varchar(255),
  DowntimeEnd               varchar(255),
  DowntimeInfo              varchar(255),
  serviceId                 varchar(255) not null,
  constraint pk_Endpoint primary key (Id)
) ;

-- AccessPolicy
create table AccessPolicy (
  Id                        varchar(255) not null,
  endpointId                varchar(255) not null,
  constraint pk_AccessPolicy primary key (Id)
) ;

-- UserDomain
create table UserDomain (
  Id                        varchar(255) not null,
  Level                     integer,
  userDomainId              varchar(255),
  constraint pk_UserDomain primary key (Id)
) ;

-- MappingPolicy
create table MappingPolicy (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Scheme                    varchar(255) not null,
  shareId                   varchar(255) not null,
  constraint pk_MappingPolicy primary key (Id)
) ;

-- Domain
create table Domain (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Description               varchar(255),
  locationId                varchar(255),
  constraint pk_Domain primary key (Id)
) ;

-- Policy
create table Policy (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Scheme                    varchar(255) not null,
  constraint pk_Policy primary key (Id)
) ;

-- Share
create table Share (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Description               varchar(255),
  serviceId                 varchar(255) not null,
  constraint pk_Share primary key (Id)
) ;

-- Manager
create table Manager (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  ProductName               varchar(255) not null,
  ProductVersion            varchar(255),
  serviceId                 varchar(255) not null,
  managerId                 varchar(255) not null,
  constraint pk_Manager primary key (Id)
) ;

-- Resource
create table Resource (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  managerId                 varchar(255) not null,
  constraint pk_Resource primary key (Id)
) ;

-- Domain_MVA
create table Domain_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Domain_MVA primary key (Id,Type,Value)
) ;

-- AdminDomain_MVA
create table AdminDomain_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_AdminDomain_MVA primary key (Id,Type,Value)
) ;

-- UserDomain_MVA
create table UserDomain_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_UserDomain_MVA primary key (Id,Type,Value)
) ;

-- Service_MVA
create table Service_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Service_MVA primary key (Id,Type,Value)
) ;

-- Endpoint_MVA
create table Endpoint_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Endpoint_MVA primary key (Id,Type,Value)
) ;

-- Policy_MVA
create table Policy_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_Policy_MVA primary key (Id,Type,Value)
) ;

-- Extension
create table Extension (
  LocalID                   varchar(255) not null,
  `Key`                     varchar(255) not null,
  Value                     varchar(255) not null,
  applicationEnvironmentId  varchar(255),
  applicationHandleId       varchar(255),
  benchmarkId               varchar(255),
  toStorageServiceId        varchar(255),
  locationId                varchar(255),
  contactId                 varchar(255),
  serviceId                 varchar(255),
  domainId                  varchar(255),
  endpointId                varchar(255),
  shareId                   varchar(255),
  managerId                 varchar(255),
  resourceId                varchar(255),
  activityId                varchar(255),
  policyId                  varchar(255),
  storageServiceCapacityId  varchar(255),
  storageAccessProtocolId   varchar(255),
  storageShareCapacityId    varchar(255),
  toComputingServiceId      varchar(255),
  constraint pk_Extension primary key (LocalID)
) ;

-- StorageService
create table StorageService (
  Id                        varchar(255) not null,
  constraint pk_StorageService primary key (Id)
) ;

-- StorageServiceCapacity
create table StorageServiceCapacity (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  TotalSize                 integer,
  FreeSize                  integer,
  UsedSize                  integer,
  ReservedSize              integer,
  storageServiceId          varchar(255) not null,
  constraint pk_StorageServiceCapacity primary key (Id)
) ;

-- StorageAccessProtocol
create table StorageAccessProtocol (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  Version                   varchar(255) not null,
  MaxStreams                integer,
  storageServiceId          varchar(255) not null,
  constraint pk_StorageAccessProtocol primary key (Id)
) ;

-- StorageEndpoint
create table StorageEndpoint (
  Id                        varchar(255) not null,
  constraint pk_StorageEndpoint primary key (Id)
) ;

-- StorageShare
create table StorageShare (
  Id                        varchar(255) not null,
  ServingState              varchar(255) not null,
  Path                      varchar(255),
  SharingID                 varchar(255) not null,
  AccessLatency             varchar(255) not null,
  DefaultLifeTime           integer,
  MaximumLifeTime           integer,
  Tag                       varchar(255),
  constraint pk_StorageShare primary key (Id)
) ;

-- StorageShareCapacity
create table StorageShareCapacity (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  Type                      varchar(255) not null,
  TotalSize                 integer,
  FreeSize                  integer,
  UsedSize                  integer,
  ReservedSize              integer,
  storageShareId            varchar(255) not null,
  constraint pk_StorageShareCapacity primary key (Id)
) ;

-- StorageManager
create table StorageManager (
  Id                        varchar(255) not null,
  constraint pk_StorageManager primary key (Id)
) ;

-- DataStore
create table DataStore (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Latency                   varchar(255) not null,
  TotalSize                 integer,
  FreeSize                  integer,
  UsedSize                  integer,
  constraint pk_DataStore primary key (Id)
) ;

-- ToComputingService
create table ToComputingService (
  Id                        varchar(255) not null,
  Name                      varchar(255),
  CreationTime              timestamp,
  Validity                  integer,
  NetworkInfo               varchar(255),
  Bandwidth                 integer,
  computingServiceId        varchar(255) not null,
  storageServiceId          varchar(255) not null,
  constraint pk_ToComputingService primary key (Id)
) ;

-- StorageShare_MVA
create table StorageShare_MVA (
  Id                        varchar(255) not null,
  Type                      varchar(255) not null,
  Value                     varchar(255) not null,
  constraint pk_StorageShare_MVA primary key (Id,Type,Value)
) ;

















































-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   mysql
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Thu Apr 23 13:21:14 2009
--     Input Files:       dia/ComputingServiceEntities.dia dia/CoreEntities.dia dia/Extension.dia dia/RelationsInComputingAndStorageServiceEntities.dia dia/RelationsInCoreEntities.dia dia/StorageServiceEntities.dia

-- alter table ComputingService add constraint computingService_fk_Id
  foreign key (Id) references
  Service (Id) for mysql
-- alter table ComputingEndpoint add constraint computingEndpoint_fk_Id
  foreign key (Id) references
  Endpoint (Id) for mysql
-- alter table ComputingShare add constraint computingShare_fk_Id
  foreign key (Id) references
  Share (Id) for mysql
-- alter table ComputingManager add constraint computingManager_fk_Id
  foreign key (Id) references
  Manager (Id) for mysql
-- alter table ExecutionEnvironment add constraint executionEnvironment_fk_Id
  foreign key (Id) references
  Resource (Id) for mysql
-- alter table ComputingActivity add constraint computingActivity_fk_Id
  foreign key (Id) references
  Activity (Id) for mysql
-- alter table ComputingEndpoint_MVA add constraint computingEndpoint_MVA_fk_Id
  foreign key (Id) references
  ComputingEndpoint (Id) for mysql
-- alter table ComputingManager_MVA add constraint computingManager_MVA_fk_Id
  foreign key (Id) references
  ComputingManager (Id) for mysql
-- alter table ExecutionEnvironment_MVA add constraint executionEnvironment_MVA_fk_Id
  foreign key (Id) references
  ExecutionEnvironment (Id) for mysql
-- alter table ApplicationEnvironment_MVA add constraint applicationEnvironment_MVA_fk_Id
  foreign key (Id) references
  ApplicationEnvironment (Id) for mysql
-- alter table ComputingActivity_MVA add constraint computingActivity_MVA_fk_Id
  foreign key (Id) references
  ComputingActivity (Id) for mysql
-- alter table ComputingShare_MVA add constraint computingShare_MVA_fk_Id
  foreign key (Id) references
  ComputingShare (Id) for mysql
-- alter table AdminDomain add constraint adminDomain_fk_Id
  foreign key (Id) references
  Domain (Id) for mysql
-- alter table UserDomain add constraint userDomain_fk_Id
  foreign key (Id) references
  Domain (Id) for mysql
-- alter table AccessPolicy add constraint accessPolicy_fk_Id
  foreign key (Id) references
  Policy (Id) for mysql
-- alter table MappingPolicy add constraint mappingPolicy_fk_Id
  foreign key (Id) references
  Policy (Id) for mysql
-- alter table Domain_MVA add constraint domain_MVA_fk_Id
  foreign key (Id) references
  Domain (Id) for mysql
-- alter table AdminDomain_MVA add constraint adminDomain_MVA_fk_Id
  foreign key (Id) references
  AdminDomain (Id) for mysql
-- alter table UserDomain_MVA add constraint userDomain_MVA_fk_Id
  foreign key (Id) references
  UserDomain (Id) for mysql
-- alter table Policy_MVA add constraint policy_MVA_fk_Id
  foreign key (Id) references
  Policy (Id) for mysql
-- alter table Endpoint_MVA add constraint endpoint_MVA_fk_Id
  foreign key (Id) references
  Endpoint (Id) for mysql
-- alter table Service_MVA add constraint service_MVA_fk_Id
  foreign key (Id) references
  Service (Id) for mysql
-- alter table Extension add constraint extension_fk_ApplicationEnvironmentId
  foreign key (applicationEnvironmentId) references
  ApplicationEnvironment (Id) for mysql
-- alter table Extension add constraint extension_fk_ApplicationHandleId
  foreign key (applicationHandleId) references
  ApplicationHandle (Id) for mysql
-- alter table Extension add constraint extension_fk_BenchmarkId
  foreign key (benchmarkId) references
  Benchmark (Id) for mysql
-- alter table Extension add constraint extension_fk_ToStorageServiceId
  foreign key (toStorageServiceId) references
  ToStorageService (Id) for mysql
-- alter table Extension add constraint extension_fk_StorageServiceCapacityId
  foreign key (storageServiceCapacityId) references
  StorageServiceCapacity (Id) for mysql
-- alter table Extension add constraint extension_fk_StorageAccessProtocolId
  foreign key (storageAccessProtocolId) references
  StorageAccessProtocol (Id) for mysql
-- alter table Extension add constraint extension_fk_StorageShareCapacityId
  foreign key (storageShareCapacityId) references
  StorageShareCapacity (Id) for mysql
-- alter table Extension add constraint extension_fk_ToComputingServiceId
  foreign key (toComputingServiceId) references
  ToComputingService (Id) for mysql
-- alter table Extension add constraint extension_fk_LocationId
  foreign key (locationId) references
  Location (Id) for mysql
-- alter table Extension add constraint extension_fk_ContactId
  foreign key (contactId) references
  Contact (Id) for mysql
-- alter table Extension add constraint extension_fk_ServiceId
  foreign key (serviceId) references
  Service (Id) for mysql
-- alter table Extension add constraint extension_fk_DomainId
  foreign key (domainId) references
  Domain (Id) for mysql
-- alter table Extension add constraint extension_fk_EndpointId
  foreign key (endpointId) references
  Endpoint (Id) for mysql
-- alter table Extension add constraint extension_fk_ShareId
  foreign key (shareId) references
  Share (Id) for mysql
-- alter table Extension add constraint extension_fk_ManagerId
  foreign key (managerId) references
  Manager (Id) for mysql
-- alter table Extension add constraint extension_fk_ResourceId
  foreign key (resourceId) references
  Resource (Id) for mysql
-- alter table Extension add constraint extension_fk_ActivityId
  foreign key (activityId) references
  Activity (Id) for mysql
-- alter table Extension add constraint extension_fk_PolicyId
  foreign key (policyId) references
  Policy (Id) for mysql
-- alter table ToComputingService add constraint toComputingService_fk_ComputingServiceId
  foreign key (computingServiceId) references
  ComputingService (Id) for mysql
-- alter table ToStorageService add constraint toStorageService_fk_ComputingServiceId
  foreign key (computingServiceId) references
  ComputingService (Id) for mysql
-- alter table ApplicationEnvironment add constraint applicationEnvironment_fk_ComputingManagerId
  foreign key (computingManagerId) references
  ComputingManager (Id) for mysql
-- alter table Benchmark add constraint benchmark_fk_ComputingManagerId
  foreign key (computingManagerId) references
  ComputingManager (Id) for mysql
-- alter table Benchmark add constraint benchmark_fk_ExecutionEnvironmentId
  foreign key (executionEnvironmentId) references
  ExecutionEnvironment (Id) for mysql
-- alter table ExecutionEnvironmentApplicationEnvironment add constraint exctnvrnmntplctnvrnmnt_fk_ExecutionEnvironmentId
  foreign key (executionEnvironmentId) references
  ExecutionEnvironment (Id) for mysql
-- alter table ExecutionEnvironmentApplicationEnvironment add constraint exctnvrnmntplctnvrnmnt_fk_ApplicationEnvironmentId
  foreign key (applicationEnvironmentId) references
  ApplicationEnvironment (Id) for mysql
-- alter table ApplicationHandle add constraint applicationHandle_fk_ApplicationEnvironmentId
  foreign key (applicationEnvironmentId) references
  ApplicationEnvironment (Id) for mysql
-- alter table ToStorageService add constraint toStorageService_fk_StorageServiceId
  foreign key (storageServiceId) references
  StorageService (Id) for mysql
-- alter table ToComputingService add constraint toComputingService_fk_StorageServiceId
  foreign key (storageServiceId) references
  StorageService (Id) for mysql
-- alter table StorageServiceCapacity add constraint storageServiceCapacity_fk_StorageServiceId
  foreign key (storageServiceId) references
  StorageService (Id) for mysql
-- alter table StorageAccessProtocol add constraint storageAccessProtocol_fk_StorageServiceId
  foreign key (storageServiceId) references
  StorageService (Id) for mysql
-- alter table StorageShareCapacity add constraint storageShareCapacity_fk_StorageShareId
  foreign key (storageShareId) references
  StorageShare (Id) for mysql
-- alter table DomainContact add constraint domainContact_fk_DomainId
  foreign key (domainId) references
  Domain (Id) for mysql
-- alter table DomainContact add constraint domainContact_fk_ContactId
  foreign key (contactId) references
  Contact (Id) for mysql
-- alter table AdminDomain add constraint adminDomain_fk_AdminDomainId
  foreign key (adminDomainId) references
  AdminDomain (Id) for mysql
-- alter table UserDomain add constraint userDomain_fk_UserDomainId
  foreign key (userDomainId) references
  UserDomain (Id) for mysql
-- alter table Service add constraint service_fk_AdminDomainId
  foreign key (adminDomainId) references
  AdminDomain (Id) for mysql
-- alter table UserDomainPolicy add constraint userDomainPolicy_fk_UserDomainId
  foreign key (userDomainId) references
  UserDomain (Id) for mysql
-- alter table UserDomainPolicy add constraint userDomainPolicy_fk_PolicyId
  foreign key (policyId) references
  Policy (Id) for mysql
-- alter table Service add constraint service_fk_LocationId
  foreign key (locationId) references
  Location (Id) for mysql
-- alter table ServiceContact add constraint serviceContact_fk_ServiceId
  foreign key (serviceId) references
  Service (Id) for mysql
-- alter table ServiceContact add constraint serviceContact_fk_ContactId
  foreign key (contactId) references
  Contact (Id) for mysql
-- alter table Domain add constraint domain_fk_LocationId
  foreign key (locationId) references
  Location (Id) for mysql
-- alter table ServiceService add constraint serviceService_fk_ServiceId
  foreign key (serviceId2) references
  Service (Id) for mysql
-- alter table ServiceService add constraint serviceService_fk_ServiceId
  foreign key (serviceId1) references
  Service (Id) for mysql
-- alter table Endpoint add constraint endpoint_fk_ServiceId
  foreign key (serviceId) references
  Service (Id) for mysql
-- alter table AccessPolicy add constraint accessPolicy_fk_EndpointId
  foreign key (endpointId) references
  Endpoint (Id) for mysql
-- alter table Activity add constraint activity_fk_EndpointId
  foreign key (endpointId) references
  Endpoint (Id) for mysql
-- alter table ActivityActivity add constraint activityActivity_fk_ActivityId
  foreign key (activityId2) references
  Activity (Id) for mysql
-- alter table ActivityActivity add constraint activityActivity_fk_ActivityId
  foreign key (activityId1) references
  Activity (Id) for mysql
-- alter table Activity add constraint activity_fk_UserDomainId
  foreign key (userDomainId) references
  UserDomain (Id) for mysql
-- alter table Manager add constraint manager_fk_ServiceId
  foreign key (serviceId) references
  Service (Id) for mysql
-- alter table Share add constraint share_fk_ServiceId
  foreign key (serviceId) references
  Service (Id) for mysql
-- alter table ShareEndpoint add constraint shareEndpoint_fk_ShareId
  foreign key (shareId) references
  Share (Id) for mysql
-- alter table ShareEndpoint add constraint shareEndpoint_fk_EndpointId
  foreign key (endpointId) references
  Endpoint (Id) for mysql
-- alter table ResourceShare add constraint resourceShare_fk_ResourceId
  foreign key (resourceId) references
  Resource (Id) for mysql
-- alter table ResourceShare add constraint resourceShare_fk_ShareId
  foreign key (shareId) references
  Share (Id) for mysql
-- alter table Activity add constraint activity_fk_ShareId
  foreign key (shareId) references
  Share (Id) for mysql
-- alter table MappingPolicy add constraint mappingPolicy_fk_ShareId
  foreign key (shareId) references
  Share (Id) for mysql
-- alter table Resource add constraint resource_fk_ManagerId
  foreign key (managerId) references
  Manager (Id) for mysql
-- alter table Activity add constraint activity_fk_ResourceId
  foreign key (resourceId) references
  Resource (Id) for mysql
-- alter table StorageService add constraint storageService_fk_Id
  foreign key (Id) references
  Service (Id) for mysql
-- alter table StorageEndpoint add constraint storageEndpoint_fk_Id
  foreign key (Id) references
  Endpoint (Id) for mysql
-- alter table StorageShare add constraint storageShare_fk_Id
  foreign key (Id) references
  Share (Id) for mysql
-- alter table DataStore add constraint dataStore_fk_Id
  foreign key (Id) references
  Resource (Id) for mysql
-- alter table StorageManager add constraint storageManager_fk_Id
  foreign key (Id) references
  Manager (Id) for mysql
-- alter table StorageShare_MVA add constraint storageShare_MVA_fk_Id
  foreign key (Id) references
  StorageShare (Id) for mysql

